/* 1. MONTHLY SUBSCRIBERS GROWTH VS. CHURN TREND  
Business Question : How has our subscriber base grown month over month 
& how many users churned each month ? */

WITH monthly_joins AS (
    SELECT 
        YEAR(CAST(registration_date AS DATE)) * 100 + 
        MONTH(CAST(registration_date AS DATE))      AS month_year,
        COUNT(user_id)                              AS new_subscribers
    FROM subscribers
    GROUP BY 
        YEAR(CAST(registration_date AS DATE)) * 100 + 
        MONTH(CAST(registration_date AS DATE))
), -- CTE to count new sign-ins per month 

monthly_churns AS (
    SELECT 
        YEAR(CAST(churn_date AS DATE)) * 100 + 
        MONTH(CAST(churn_date AS DATE))             AS month_year, -- converting date to YYYY-MM format to group the data by month easily 
        COUNT(user_id)                              AS churned_users
    FROM subscribers
    WHERE churn_date IS NOT NULL
    GROUP BY 
        YEAR(CAST(churn_date AS DATE)) * 100 + 
        MONTH(CAST(churn_date AS DATE))
) -- CTE to count how many users churned each month 
-- Combine both sets of data to calcuate net growth and total base 
SELECT 
    j.month_year,
    j.new_subscribers,
	-- COALESCE handles months where 0 users churned 
    COALESCE(c.churned_users, 0)                    AS churned_users,
	-- Net Growth = New joins minus those who churned 
    j.new_subscribers - COALESCE(c.churned_users, 0) AS net_growth,
	-- Running total of subscribers base over time 
    SUM(j.new_subscribers - COALESCE(c.churned_users, 0))
        OVER (ORDER BY j.month_year)                AS running_total_subscribers
FROM monthly_joins j
-- Using LEFT JOIN to ensure every month we had signups even if noone churned as in to not skip any month at all using inner join we would have skipped months 
LEFT JOIN monthly_churns c ON j.month_year = c.month_year
ORDER BY j.month_year;





/*Q2. REVENUE BY SUBSCRIPTION PLAN 
Business Question: What is the total and average monthly  revenue generated by each subscription plan?*/
SELECT 
     subscription_plan,
	 COUNT(user_id) AS total_subscribers , -- count of unique users in each subscription plan 
	 SUM (monthly_price_inr ) as total_revenue , -- total monthly revenue 
	 -- count of users in each plan / count of users accross all plans * 100 
	 ROUND(CAST(COUNT(user_id) AS FLOAT ) / SUM(COUNT(user_id)) OVER () *100,2) AS subscriber_share_pct, 
	 -- revenue generated from each plan / revenue generated from all the plans * 100 
	 ROUND(CAST(SUM(monthly_price_inr) AS FLOAT )/ SUM(SUM(monthly_price_inr)) OVER () * 100,2) AS revenue_share_pct

FROM subscribers
GROUP BY subscription_plan
ORDER BY total_revenue DESC; 

/* Q2 REVISED: ACTUAL REVENUE BY PLAN (SUCCESSFUL PAYMENTS ONLY) */
SELECT 
    plan_at_payment AS subscription_plan, -- Using the plan they had AT the time of payment
    COUNT(DISTINCT user_id) AS unique_paying_subscribers,
    SUM(amount_inr) AS total_actual_revenue, 
    
    -- Subscriber Share (Based on successful payments)
    ROUND(
        CAST(COUNT(DISTINCT user_id) AS FLOAT) / 
        SUM(COUNT(DISTINCT user_id)) OVER () * 100, 2
    ) AS subscriber_share_pct,
    
    -- Revenue Share (Actual money collected)
    ROUND(
        CAST(SUM(amount_inr) AS FLOAT) / 
        SUM(SUM(amount_inr)) OVER () * 100, 2
    ) AS revenue_share_pct

FROM payments
WHERE payment_status = 'Success' -- CRITICAL: Exclude failed payments
GROUP BY plan_at_payment
ORDER BY total_actual_revenue DESC;

/*Q3. CHURN RATE BY SUBSCRIPTION PLAN 
Business Question : Which subscrption plan contributes to most churn rate */

SELECT 
    subscription_plan,
    COUNT(user_id)                                   AS total_subscribers,
    SUM(CAST(churned AS INT))                        AS churned_users,
	-- churned users / total users * 100 
    ROUND(CAST(SUM(CAST(churned AS INT)) AS FLOAT) 
          / COUNT(user_id) * 100, 2)                 AS churn_rate_pct
FROM subscribers
GROUP BY subscription_plan
ORDER BY churn_rate_pct DESC;

/* TOP 5 STATES BY SUBSCRIBERS COUNT 
Q4. Top 5 states by subscriber count and total_revenue this is only monthly revenue */

SELECT TOP 5
    state,
    COUNT(user_id)         AS total_subscribers,
    SUM(monthly_price_inr) AS total_revenue
FROM subscribers
GROUP BY state
ORDER BY total_revenue DESC; 

/*Q5. PAYMENT FAILURE ANALYSIS 
Business Question : How much money are we losing to failed payments ? */

SELECT payment_status , 
COUNT (payment_id) AS total_transactions ,
SUM (amount_inr) AS total_attempted_amount_inr 
FROM payments 
GROUP BY payment_status 
ORDER BY total_transactions ; 

/*Q6. CUSTOMER LIFETIME VALUE BY ACQUISITION CHANNEL  */

SELECT 
    s.acquisition_channel,
    COUNT(DISTINCT s.user_id) AS total_subscribers,
	-- difference of days between registration date and churn date 
    ROUND(AVG(CAST(DATEDIFF(day, CAST(s.registration_date AS DATE),
	-- is null is added as there maybe customers who did not churn at all so null handles those customers 
          ISNULL(CAST(s.churn_date AS DATE), 
          CAST('2024-12-31' AS DATE))) AS FLOAT)), 0) AS avg_days_active,
    SUM(p.amount_inr) AS total_revenue,
	-- Total Revenue / Total Unique Users 
    ROUND(CAST(SUM(p.amount_inr) AS FLOAT) / COUNT(DISTINCT s.user_id), 2) AS revenue_per_user
FROM subscribers s
LEFT JOIN payments p -- used left join to see all users even if they havent hade a successful payment 
    ON s.user_id = p.user_id AND p.payment_status = 'Success'
GROUP BY s.acquisition_channel
ORDER BY revenue_per_user DESC;


/* Q7. COHORT RETENTION ANALYSIS 
Business Question: Of the users who joined in a given month,
what percentage are still active after 1, 2, and 3 months? */

WITH cohort_base AS (
    SELECT
        user_id,
        CAST(DATEFROMPARTS(
            YEAR(CAST(registration_date AS DATE)),
            MONTH(CAST(registration_date AS DATE)), 1) AS DATE)     AS cohort_month
    FROM subscribers
),-- Logic : create a cohort for each user based on their join month 
-- consider all the registration dates from the 1st of every month and then consider it as cohort month 
cohort_activity AS (
    SELECT
        cb.cohort_month,
        COUNT(DISTINCT cb.user_id)                                  AS cohort_size,
        COUNT(DISTINCT CASE 
            WHEN s.churn_date IS NULL 
              OR DATEDIFF(day, CAST(s.registration_date AS DATE), 
                               CAST(s.churn_date AS DATE)) > 30 
            THEN cb.user_id END)                                     AS retained_m1, -- people who stayed more than 30 days 
        COUNT(DISTINCT CASE 
            WHEN s.churn_date IS NULL 
              OR DATEDIFF(day, CAST(s.registration_date AS DATE), 
                               CAST(s.churn_date AS DATE)) > 60 
            THEN cb.user_id END)                                     AS retained_m2,-- people who stayed more than 60 days 
        COUNT(DISTINCT CASE 
            WHEN s.churn_date IS NULL 
              OR DATEDIFF(day, CAST(s.registration_date AS DATE), 
                               CAST(s.churn_date AS DATE)) > 90 
            THEN cb.user_id END)                                     AS retained_m3 -- people who stayed more than 90 days 
    FROM cohort_base cb
    JOIN subscribers s ON cb.user_id = s.user_id
    GROUP BY cb.cohort_month
)
SELECT
    cohort_month,
    cohort_size,
    retained_m1,
    ROUND(CAST(retained_m1 AS FLOAT) / cohort_size * 100, 1)    AS retention_rate_m1_pct, -- retention percentage calculated 
    retained_m2,
    ROUND(CAST(retained_m2 AS FLOAT) / cohort_size * 100, 1)    AS retention_rate_m2_pct, -- retention percentage calculated
    retained_m3,
    ROUND(CAST(retained_m3 AS FLOAT) / cohort_size * 100, 1)    AS retention_rate_m3_pct -- retention percentage calculated 
FROM cohort_activity
ORDER BY cohort_month;



/*Q8. USER ENGAGEMENT VS CHURN RATE 
Business Question : Does Average watch time affect engagement rate */
SELECT
      s.churned , 
	  COUNT (s.user_id) AS total_users, -- total count of users in each category 
	  -- average duration of each watch session 
	  -- avearge durations accross all sessions 
	  ROUND(AVG(CAST(w.watch_duration_mins AS FLOAT )),2) AS avg_session_duration,
	  -- average number of sessions per user 
	  ROUND(CAST(COUNT(w.session_id) AS FLOAT) / COUNT(DISTINCT s.user_id),1) AS avg_sessions_per_user
FROM subscribers s

LEFT JOIN watch_history w
ON s.user_id = w.user_id 
GROUP BY s.churned; 



/*Q9. ISSUE TYPE VS CHURN RATE 
Business Question : What kind of issues actually lead to higher churn rate amongst the users who have encountered problems*/

SELECT 
    t.issue_type, 
    COUNT(DISTINCT t.user_id) AS total_users_who_complained,

    -- count only users who churned after complaining 
    COUNT(DISTINCT CASE WHEN s.churned = 1 THEN s.user_id END) AS unique_churned_users,

    -- churn rate per issue type 
    ROUND(CAST(COUNT(DISTINCT CASE WHEN s.churned = 1 THEN s.user_id END) AS FLOAT) 
          / COUNT(DISTINCT t.user_id) * 100, 2) AS churn_rate_pct

FROM support_tickets t
JOIN subscribers s ON t.user_id = s.user_id
GROUP BY t.issue_type
ORDER BY churn_rate_pct DESC;

/*Q10. LANGUAGE PREFERENCE VS CHURN RATE 
Business Question : Regional content consumers are more loyal or not */

SELECT 
      s.language_preference,
	  -- average wallet share of a user in the language group 
	  ROUND(AVG(p.total_spent),2) AS avg_customer_value,
	  -- total churn in language / total users in language 
	  ROUND(CAST(SUM(CAST(s.churned AS INT )) AS FLOAT) / COUNT (s.user_id) *100,2) AS churn_rate_pct
	  FROM subscribers s
	  -- We pre-calculate the total successful spend for EACH user first.
	  LEFT JOIN (
	             SELECT user_id , SUM(amount_inr) AS total_spent
				 FROM payments 
				 WHERE payment_status = 'Success'
				 GROUP BY user_id 
				 ) p
				 ON p.user_id = s.user_id 
				 GROUP BY s.language_preference -- Grouping by language to compare the "Value" of different regional markets
				 ORDER BY avg_customer_value DESC; -- Sorting by the most profitable language groups first


/*Q11. EARLY CHURN WARNING SIGNALS
Business Question : Which behavioural signals appear in the weeks before a suer churns and how early do they appear ?*/

WITH user_last_activity AS (
      SELECT 
	        w.user_id,
			MAX(CAST(w.watch_date AS DATE )) AS last_watch_date,
			AVG(CAST(w.watch_duration_mins AS FLOAT )) AS avg_watch_duration
	   FROM watch_history w
	   GROUP BY w.user_id 

	   ), 
	   user_payment_risk AS (
	   SELECT 
	         user_id, 
			 SUM (
			       CASE 
				       WHEN payment_status = 'Failed' THEN 1
					   ELSE 0
					END
                   ) AS failed_payment_count 
		FROM payments
		GROUP BY user_id 
		), 
		user_support_risk AS (
		SELECT 
		      user_id, 
			  COUNT(ticket_id) AS total_tickets, 
			  SUM(
			       CASE 
				       WHEN issue_type = 'Cancellation Request' THEN 1
					   ELSE 0
					END 
					) AS cancellation_requests
		 FROM support_tickets
		 GROUP BY user_id 
		 )

		 -- main query 

		 SELECT 
		 s.user_id, s.subscription_plan, s.acquisition_channel, s.churned, s.churn_date,
		 DATEDIFF(
		       day, 
			   la.last_watch_date,
			   ISNULL(CAST(s.churn_date AS DATE ),
			        CAST ('2024-12-31' AS DATE))
					)                                AS days_inactive_before_churn,
					ROUND (la.avg_watch_duration, 1) AS avg_watch_duration_mins,
					COALESCE(pr.failed_payment_count, 0) AS failed_payment_count, 
					COALESCE (sr.cancellation_requests,0) AS cancellation_requests
		FROM subscribers s
		LEFT JOIN user_last_activity la ON s.user_id = la.user_id
		LEFT JOIN user_payment_risk pr ON s.user_id = pr.user_id
		LEFT JOIN user_support_risk sr ON s.user_id = sr.user_id
		WHERE s.churned = 1
		ORDER BY days_inactive_before_churn DESC; 
